config/routes.rb
Rails.application.routes.draw do

  devise_for :users 

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :post_comments
  resources :posts 
  resources :categories
  resources :tags
  resources :taggings

  get 'pages/about'
  get 'pages/contact'
  get 'pages/resources'
  
  get 'categories/index'
  get 'categories/new'
  get 'categories/edit'
  get 'categories/show'
  
  get 'home/index'
    
  get '/about' , :to => 'pages#about'
  get '/contact' , :to => 'pages#contact'
  get '/resources' , :to => 'pages#resources'
  get 'tagged', :to => 'posts#tagged', :as => :tagged
  get 'posts/:id/like', :to => 'posts#liked', :as => :liked
  get 'posts/:id/unlike', :to => 'posts#unliked', :as => :unliked

  root :to => 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  # has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, 
  #       :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:email]
  #def email_required?
  	#false
  #end

  #def password_required?
  	#false
  #end
end

app/models/category.rb
class Category < ActiveRecord::Base
	attr_accessible :name
	has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	attr_accessible :title, :body, :category_id, :user_id, :tag_list
	acts_as_taggable
	acts_as_votable

	belongs_to :category
	#belongs_to :admin_user
	belongs_to :user
	has_many :post_comments, :dependent => :destroy 
	# All comments under the post get deleted if the post is deleted

	validates_presence_of :title 
	validates_length_of :body, :minimum => 10
end

app/models/post_comment.rb
class PostComment < ActiveRecord::Base
  attr_accessible :body, :post_id, :user_id
  
  belongs_to :post
  belongs_to :user
  
  validates_presence_of :body
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :login
  acts_as_voter

  has_many :posts, :dependent => :destroy 
  has_many :post_comments, :dependent => :destroy 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  def login=(login)
    @login = login
  end

  def login
    @login || self.name || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(name) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_hash).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :all_categories
  helper_method :recent_posts
  helper_method :popular_tags

  before_filter :site_search

  def site_search
    @q = Post.ransack(params[:q])
    @q_posts = @q.result(distinct:true).order("created_at DESC")
  end 

  def all_categories
  	@categories = Category.all
  end

  def popular_tags
    ActsAsTaggableOn::Tag.most_used(10)
  end

  def recent_posts
  	@posts = Post.all.order("created_at DESC").limit(10)
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :name, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @title = @category.name
    @posts = @category.posts
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #before_filter :authenticate_user!

  def index
  	@posts = Post.all.order("created_at DESC")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  	@posts = Post.all
  	@categories = Category.all
  end

  def contact
  	@posts = Post.all
  	@categories = Category.all
  end

  def resources
  	@posts = Post.all
  	@categories = Category.all
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < InheritedResources::Base
  def create
	@post_comment = current_user.post_comments.build(params[:post_comment])
	if @post_comment.save
		redirect_to @post_comment.post, :notice => "Comment was successfully created."
	else
		redirect_to @post_comment.post, :notice => "Error creating post_comment : #{@post_comment.errors}."	
	end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show, :tagged]
	
	def index
		@q = Post.ransack(params[:q])
		@posts = @q.result(distinct:true).order("created_at DESC")
	end

	def show
		@post = Post.find(params[:id])
		@user = User.all
		@post_comment = PostComment.new(:post_id => @post.id)
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(params[:post])
		if @post.save
			redirect_to posts_path, :notice => "Your post has been saved."
		else
			render "new"
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update_attributes(params[:post])
			redirect_to post_path, :notice => "Your post has been updated."
		else
			render "edit"
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path, :notice => "Your post has been deleted."
	end

	def tagged
		if params[:tag].present?
			@posts = Post.tagged_with(params[:tag])
		else
			@posts = Post.all
		end
	end

	def liked 
		@post = Post.find(params[:id])
		@post.liked_by current_user
		redirect_to posts_path
	end

	def unliked
		@post = Post.find(params[:id])
		@post.unliked_by current_user
		redirect_to posts_path
	end 
	#def tags
	#	@users = User.where("LOWER(name) LIKE ?", "%#{params[:q]}%").order(:name)
	#	@categories = Category.where("name LIKE ?", "%#{params[:q]}%").order(:name)
	#	respond_to do |format|
	#		format.json {render :json => @users + @categories, :only =>[:id, :name]}
	#	end
	#end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/categories/index.html.erb
<div class="post">
<h1>Listing categories</h1>
<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.name, category %></li>
  <% end %>
</ul>
</div>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<% if @posts.each do |post| %>
	<div class="post">
		<h2 class="title"><%= link_to post.title, post %> </h2>
		<div class="entry"><%= post.body %></div>
	</div>
	<br>
	<% end.empty? %>
		<p>Sorry, there are no posts in this category.</p>
	<% end %>
<%= link_to "Back to Categories", categories_path %>

app/views/home/index.html.erb
<% @posts.each do |post| %>
<div class="post">
	<h2 class="title"><%= link_to post.title, post %></h2>

	<div class = "tag">
	  <% if post.tags.any? %>
	    <% post.tags.each do |tag| %>
	      <% if Category.find_by_name(tag.name) %>
          	<%= link_to "#"+tag.name, tagged_url(:tag => tag.name) %>
	      <% else  %>
	        <% if User.find_by_name(tag.name) %>
	          <%= link_to "@"+tag.name, tagged_url(:tag => tag.name) %>
	        <% else %>
	          <%= link_to tag.name, tagged_url(:tag => tag.name) %>
	        <% end %>
	      <% end %>
	    <% end %>
	  <% end %>
	</div>

	<div class="entry"><%= post.body %></div>
	<div class="byline">
        <p class="meta"><%= post.created_at.strftime("%b %d %Y") %><!-- Posted by <%= post.user.name %>--></p>
        <p class="links"><%= link_to "Read More", post %>
        <% if user_signed_in? %>
         | <%= link_to "Comment", post %></p>
         <% end %>
    </div>
</div>
<br>
<% end %>

app/views/layouts/application.html.erb
<%= render "partials/header" %>
  <div id="page">
   <div id="page-bgtop">
    <div id="page-bgbtm">
     <div id="content">
      
     	<div class="flash-message">
     		<% flash.each do |key, value| %>
  			<p><%= value %></p>
  			<% end %>
		  </div>  

      <!-- For Devise 
      <p class="notice"><%= notice %></p>
    	<p class="alert"><%= alert %></p> -->

	    <%= yield %> <!-- main view -->
	    <div style="clear: both;">&nbsp;</div>
     </div>
     <!-- end #content -->
  
     <%= render "partials/sidebar" %>
     <div style="clear: both;">&nbsp;</div>

    </div>
    
   </div>
  </div>
  <!-- end #page-->
  <div id="footer">
   <p>Copy: 2013, My Ruby Blog -Sample Project</p>
  </div>
  <!-- en #footer-->
 </div>
 <!-- end #wrapper-->
</body>
</html>

app/views/pages/about.html.erb
<div class="post">
    <h1>About My Ruby Blog</h1>
    <p>Wondering why Ruby is so popular? Its fans call it a beautiful, artful
  language. And yet, they say it’s handy and practical. What gives?</p>

  <h3>The Ideals of Ruby’s Creator</h3>

  <p class="links">Ruby is a language of careful balance. Its creator, <a href="http://www.rubyist.net/~matz/">Yukihiro “Matz”
  Matsumoto</a>, blended parts of his favorite languages (Perl, Smalltalk,
  Eiffel, Ada, and Lisp) to form a new language that balanced functional
  programming with imperative programming.</p>

  <p>He has often said that he is “trying to make Ruby natural, not simple,”
  in a way that mirrors life.</p>

  <p>Building on this, he adds:</p>

  <blockquote>
    <p class="links">Ruby is simple in appearance, but is very complex inside, just like
  our human body<sup><a href="#fn1">1</a></sup>.</p>
  </blockquote>

  <h3>About Ruby’s Growth</h3>

  <p>Since its public release in 1995, Ruby has drawn devoted coders
  worldwide. In 2006, Ruby achieved mass acceptance. With active user
  groups formed in the world’s major cities and Ruby-related conferences
  filled to capacity.</p>

  <p style="float:right"><img src="http://gmane.org/plot-rate.php?group=gmane.comp.lang.ruby.general&amp;width=320&amp;height=160&amp;title=Ruby-Talk+Activity" alt="Graph courtesy of
  Gmane." title="Graph courtesy of Gmane." style="padding-left:8px;" /></p>

  <p class="links">Ruby-Talk, the primary <a href="/en/community/mailing-lists/">mailing list</a> for
  discussion of the Ruby language, climbed to an average of 200 messages
  per day in 2006. It has dropped in recent years as the size of the
  community pushed discussion from one central list into many smaller
  groups.</p>

  <p class="links">Ruby is ranked among the top 10 on most of the indices that measure
  the growth and popularity of programming languages worldwide
  (such as the <a href="http://www.tiobe.com/index.php/content/paperinfo/tpci/index.html">TIOBE index</a>). Much of the growth is attributed to the
  popularity of software written in Ruby, particularly the
  <a href="http://rubyonrails.org/">Ruby on Rails</a> web framework.</p>

  <p class="links">Ruby is also <a href="/en/about/license.txt">completely free</a>. Not only free of charge, but
  also free to use, copy, modify, and distribute.</p>

  <h3>Beyond the Basics</h3>

  <p>Ruby has a wealth of other features, among which are the following:</p>

  <ul>
    <li>
      <p>Ruby has exception handling features, like Java or Python, to make it
  easy to handle errors.</p>
    </li>
    <li>
      <p>Ruby features a true mark-and-sweep garbage collector for all Ruby
  objects. No need to maintain reference counts in extension libraries.
  As Matz says, “This is better for your health.”</p>
    </li>
    <li>
      <p>Writing C extensions in Ruby is easier than in Perl or Python, with a
  very elegant API for calling Ruby from C. This includes calls for
  embedding Ruby in software, for use as a scripting language. A SWIG
  interface is also available.</p>
    </li>
    <li>
      <p>Ruby can load extension libraries dynamically if an OS allows.</p>
    </li>
    <li>
      <p>Ruby features OS independent threading. Thus, for all platforms on
  which Ruby runs, you also have multithreading, regardless of if the OS
  supports it or not, even on MS-DOS!</p>
    </li>
    <li>
      <p>Ruby is highly portable: it is developed mostly on GNU/Linux, but
  works on many types of UNIX, Mac OS X, Windows 95/98/Me/NT/2000/XP,
  DOS, BeOS, OS/2, etc.</p>
    </li>
  </ul>

  <h3>References</h3>

  <p  class="links" id="fn1"><sup>1</sup> Matz, speaking on the Ruby-Talk mailing list, <a href="http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-talk/2773">May 12th,
  2000</a>.</p>

  <p  class="links" id="fn2"><sup>2</sup> Matz, in <a href="http://www.linuxdevcenter.com/pub/a/linux/2001/11/29/ruby.html">An Interview with the Creator of Ruby</a>, Nov.
  29th, 2001.</p>

  <p  class="links" id="fn3"><sup>3</sup> Matz, in <a href="http://www.artima.com/intv/closures2.html">Blocks and Closures in Ruby</a>, December 22nd,
  2003.</p>
</div>

app/views/pages/contact.html.erb
<div class="post">
	<h1>Pages#contact</h1>
	<p>Find me in app/views/pages/contact.html.erb</p>
</div>

app/views/pages/resources.html.erb
<div class="post">
	<h1>Pages#resources</h1>
	<p>Find me in app/views/pages/resources.html.erb</p>
</div>

app/views/partials/_comment.html.erb
<div class="comment">
	<i><%= simple_format h(comment.body) %></i>
</div>

app/views/partials/_comment_edit.html.erb
<%= form_for @post_comment do |f| %>
	<%= f.hidden_field :post_id %>
    <%= f.hidden_field :user_id %>
    <p>
      <%= f.text_field :body %>
    </p>
    <br />
    <p>
      <%= f.submit "Update Comment" %>
    </p>
    <br />
<% end %>

app/views/partials/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Ruby Blog</title>
   <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Abel" type="text/css" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>

<body>
<div id="wrapper">
  <div id="header-wrapper">
   <div id="header">
    <div id="logo">
     <h1><a>My Ruby Blog</a></h1>
     <p>Learing Ruby on Rails</p>
    </div>
    <div id="menu">
		<ul class="main-nav">
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Blog", posts_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "Resources", resources_path %></li>
		</ul>
	</div>
   </div>
  </div>
  <!-- end #header -->

app/views/partials/_sidebar.html.erb
<div id="sidebar">
  <ul class="nav pull-right">
    <% if user_signed_in? %>
        <li>
            Signed in as : <%= link_to current_user.name, edit_user_registration_path %>
        </li>
        <li><%= button_to "Logout", destroy_user_session_path, :method => :delete %></li>
    <% else %>
      <li>
        <table>
          <tr>
            <th>
              <td>
                <%= button_to "Sign in", new_user_session_path, :method => :get %>
              </td>
              <td>
                 <%= button_to "Sign up", new_user_registration_path, :method => :get %>
              </td>
            </th>
          </tr>
        </table>
      </li>
    <% end %>
  </ul>
  <ul>
    <li>
        <div id="search">
          <%= search_form_for @q do |f| %>
          <%= f.text_field :title_or_body_cont %>
          <br />
          <%= f.submit "Search" %>
          <% end %>
        </div>
        <div style="clear: both;">&nbsp;</div>
       </li>
       <li>
        <h2>Categories</h2>
        <ul>
          <% all_categories.each do |cat| %>
            <li><%= link_to cat.name, category_path(:id => cat.id) %></li>
          <% end %>
        </ul>
       </li>
       <li>
        <h2>Popular Tags</h2>
        <ul>
          <% popular_tags.each do |tag| %>
            <li><%= link_to tag.name, tagged_url(:tag => tag.name) %></li>
          <% end %>
        </ul>
       </li>
       <li>
        <h2>Recent Posts</h2>
        <ul>
         <% recent_posts.each do |post| %>
            <li><%= link_to post.title, post_path(:id => post.id) %></li>
          <% end %>
        </ul>
       </li>

      </ul>
     </div>
     <!-- end #sidebar -->

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for @post do |f| %>
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %><br />
	</p>
	<p>
		<%= f.label :tag_list, "Tags (separated by commas)" %><br />
		<%= f.text_field :tag_list %><br />
	</p>
	<p>
		<%= f.label :body %><br />
		<%= f.text_area :body %><br />
	</p>
	<p>
		<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => "Select One"} %><br />
	</p>
	<p>
		<%= f.submit "Update Post" %><br />
	</p>
<% end %>
<%= link_to "Go Back", post_path %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="post">
  <h2 class="title"><%= link_to post.title, post %></h2>
  
  <div class = "tag">
    <% if post.tags.any? %>
      <% post.tags.each do |tag| %>
        <% if Category.find_by_name(tag.name) %>
          <!--<%= link_to "#"+tag.name, category_path(:id => Category.find_by_name(tag.name).id) %> Go to categories#show-->
          <%= link_to "#"+tag.name, tagged_url(:tag => tag.name) %>
        <% else %>
          <% if User.find_by_name(tag.name) %>
            <%= link_to "@"+tag.name, tagged_url(:tag => tag.name) %>
          <% else %>
            <%= link_to tag.name, tagged_url(:tag => tag.name) %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  
  <div class="entry"><%= post.body %></div>
  <div class="byline">
        <p class="meta"><%= post.created_at.strftime("%b %d %Y") %><!--Posted by <%= post.user.name %>--></p><br />
        <p><%= post.get_likes.size %> Like(s), <%= post.get_dislikes.size %> Dislike(s)</p>
        <p class="links"><%= link_to "Read More", post %>
          <% if user_signed_in? %>
           | <%= link_to "Comment", post %>
            <% if current_user.liked? post %>
              | <%= link_to "Unlike", unliked_url(post), method: :put %>
            <% else %>
              | <%= link_to "Like", liked_url(post), method: :put %>
            <% end %>
          <% end %>
        </p>
  </div>  
</div>
<br />
<% end %>
<% if user_signed_in? %>
	<p><%= link_to "Add New Post", new_post_path %></p>
<% end %>

app/views/posts/new.html.erb
<h1>Add New Post</h1>
<%= form_for @post do |f| %>
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %><br />
	</p>
	<p>
		<%= f.label :tags, "Tags (separated by commas)" %><br />
		<%= f.text_field :tag_list %><br />
	</p>
	<p>
		<%= f.label :body %><br />
		<%= f.text_area :body %><br />
	</p>
	<p>
		<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => "Select One"} %><br />
	</p>
	<p>
		<%= f.submit "Add Post" %><br />
	</p>
<% end %>

app/views/posts/show.html.erb
<div class="post">
<h1><%= @post.title %></h1>
<br />
<small><%= @post.created_at.strftime("%b %d %Y") %></small>

<div class = "tag">
  <% if @post.tags.any? %>
    <% @post.tags.each do |tag| %>
      <% if Category.find_by_name(tag.name) %>
        <%= link_to "#"+tag.name, tagged_url(:tag => tag.name) %>
      <% else  %>
        <% if User.find_by_name(tag.name) %>
          <%= link_to "@"+tag.name, tagged_url(:tag => tag.name) %>
        <% else %>
          <%= link_to tag.name, tagged_url(:tag => tag.name) %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

<!--<p style="color: grey;">Posted By : <%= @post.user.name %></p>-->
<p><%= @post.body %></p>
<p style="color: grey;">Tag : <%= link_to @post.category.name, category_path(:id => @post.category.id) %></p>
<p><%= link_to "Back", posts_path %>
<% if @post.user == current_user %> 
| <%= link_to "Edit Post", edit_post_path %> | <%= link_to "Delete", @post, :confirm => "Are you sure you want to delete?", :method => :delete %> 
<% end %>
</p>
<p>
  <%= @post.post_comments.count %> comment(s)
</p>
<% if user_signed_in? %>
  <h3>Add a Comment</h3>
  <br />
  <%= form_for @post_comment do |f| %>
    <%= f.hidden_field :post_id %>
    <%= f.hidden_field :user_id %>
    <p>
      <%= f.text_field :body %>
    </p>
    <br />
    <p>
      <%= f.submit "Post Comment" %>
    </p>
    <br />
  <% end %>
<% end %>
<%= render :partial => 'partials/comment', :collection => @post.post_comments %>
</div>

app/views/posts/tagged.html.erb
<% @posts.each do |post| %>
<div class="post">
  <h2 class="title"><%= link_to post.title, post %></h2>
  
  <div class = "tag">
    <% if post.tags.any? %>
      <% post.tags.each do |tag| %>
        <% if Category.find_by_name(tag.name) %>
          <%= link_to "#"+tag.name, tagged_url(:tag => tag.name) %>
        <% else  %>
          <% if User.find_by_name(tag.name) %>
            <%= link_to "@"+tag.name, tagged_url(:tag => tag.name) %>
          <% else %>
            <%= link_to tag.name, tagged_url(:tag => tag.name) %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  
  <div class="entry"><%= post.body %></div>
  <div class="byline">
        <p class="meta"><%= post.created_at.strftime("%b %d %Y") %><!--Posted by <%= post.user.name %>--></p>
        <p class="links"><%= link_to "Read More", post %>
        <% if user_signed_in? %>
         | <%= link_to "Comment", post %></p>
        <% end %>
  </div>  
</div>
<br />
<% end %>
<% if user_signed_in? %>
	<p><%= link_to "Add New Post", new_post_path %></p>
<% end %>